language: csharp
solution: Source/SharpNav.sln
sudo: false # Use container-based infrastructure

notifications:
  slack:
    secure: Evj0iL40Tipu47BZfCdbkZbW/8Y7NLRZRSjvLXhKH7Yc6DfYLWeF7+Y2h8E8Zdd2/bdP+LxlHTbqjam5IBONAAIwpN4TAXNqMmalXtXDfs3/Cu+pMKSN+ECymcX3bUa/cZyvjm8P4FfUWLDHKuk+I3C41DfXzTPRBg4z+qSg4kI=

env:
  matrix:
   - XBUILD_TARGET=Standalone
   - XBUILD_TARGET=OpenTK
   - XBUILD_TARGET=SharpDX
   - XBUILD_TARGET=MonoGame

install:
 - travis_retry nuget restore Build/CI/$XBUILD_TARGET.packages.config -SolutionDirectory Source/
 - travis_retry nuget install NUnit.Runners -OutputDirectory test -ExcludeVersion
script:
 - xbuild /t:$XBUILD_TARGET /verbosity:minimal ./Build/CoreOnly.proj
 - mono ./test/NUnit.Runners/tools/nunit-console.exe ./Binaries/Tests/$XBUILD_TARGET/SharpNav.Tests.dll -exclude BrokenButUnused
