language: csharp
solution: SharpNav.sln

notifications:
  slack:
    secure: Evj0iL40Tipu47BZfCdbkZbW/8Y7NLRZRSjvLXhKH7Yc6DfYLWeF7+Y2h8E8Zdd2/bdP+LxlHTbqjam5IBONAAIwpN4TAXNqMmalXtXDfs3/Cu+pMKSN+ECymcX3bUa/cZyvjm8P4FfUWLDHKuk+I3C41DfXzTPRBg4z+qSg4kI=

env:
  matrix:
   - XBUILD_TARGET=Standalone
   - XBUILD_TARGET=OpenTK
   - XBUILD_TARGET=SharpDX
   - XBUILD_TARGET=MonoGame

install:
# - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
# - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
# - echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
# - sudo apt-get update -qq
# - sudo apt-get install mono-devel nunit-console
# - mozroots --import --sync
 - sudo apt-get install nunit-console
 - nuget restore SharpNav.sln
script:
 - xbuild ./Build/TravisCI.proj /t:$XBUILD_TARGET
 - nunit-console ./Binaries/Tests/$XBUILD_TARGET/SharpNavTests.dll -exclude BrokenButUnused
