language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console

script:
  - xbuild ./Build/TravisCI.proj
  - nunit-console ./Binaries/Tests/Standalone/SharpNavTests.dll -exclude BrokenButUnused