version: 1.0.0-alpha.1+appveyor.{build}

branches:
  only:
    - master
    
before_build:
  - nuget restore Source/SharpNav.sln
  
configuration:
  - Standalone
  - OpenTK
  - SharpDX
  - MonoGame
  
platform:
  - Any CPU
  
build:
  project: Build/CoreOnly.proj
#  parallel: true
  verbosity: normal
  
test:
  categories:
    except:
      - BrokenButUnused
      
deploy: off