version: 1.0.0-alpha.1+appveyor.{build}

branches:
  only:
    - master
    
before_build:
  - nuget restore Source/SharpNav.sln
  
configuration:
  - Standalone
  - OpenTK
  - SharpDX
  - MonoGame
  
build:
  - msbuild "Build/CoreOnly.proj" /p:Configuration=$(CONFIGURATION) /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test:
  categories:
    except:
      - BrokenButUnused
      
deploy: off